# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityScheduleAndCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True)),
                ('to_date', models.DateField(blank=True)),
                ('from_time', models.TimeField(blank=True)),
                ('to_time', models.TimeField(blank=True)),
                ('activity', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('activities', models.CharField(blank=True, max_length=255, null=True)),
                ('target_group', models.CharField(blank=True, max_length=255, null=True)),
                ('course_outline', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
