# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_and_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityScheduleAndCalendar',
            new_name='Activity',
        ),
    ]
